generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/aws-iam
inputSpec: modules/openapi-generator/src/test/resources/3_0/typescript-axios/petstore-with-aws-iam.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-axios
